cpp:
	g++ *.cpp -g -lm

c:
	gcc *.c -g -lm

cpp-s:
	mv -f *.cpp success/
	rm -f *.out
	> input

cpp-f:
	mv -f *.cpp fail/
	rm -f *.out
	> input

c-s:
	mv -f *.c success/
	rm -f *.out
	> input

c-f:
	mv -f *.c fail/
	rm -f *.out
	> input
